// House of Achen — Crochet Pattern Library
// Stores uploaded pattern files locally in IndexedDB so app deployments do not erase them.
(() => {
  'use strict';
  const DB_NAME='house-of-achen-crochet',DB_VERSION=1,STORE='patterns',MAX_FILE_BYTES=50*1024*1024;
  const CATEGORIES=['Amigurumi','Home & Decor','Wearables','Accessories','Bags','Gifts','Stitches & Reference','Other'];
  const STATUSES=['Saved','Next up','Working on it','Made'];
  let crochetFilters={search:'',category:'All',status:'All'},crochetViewerUrl=null;
  const crochetEsc=(value='')=>String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
  const crochetId=()=>`pat_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
  const crochetTitleFromName=(name='Pattern')=>name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()||'Untitled pattern';
  function crochetFormatBytes(bytes=0){if(!bytes)return'0 KB';const units=['B','KB','MB','GB'],i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return`${(bytes/Math.pow(1024,i)).toFixed(i?1:0)} ${units[i]}`}
  function crochetDate(iso){if(!iso)return'';return new Date(iso).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
  function crochetFileKind(rec){const type=rec?.mimeType||'',name=(rec?.fileName||'').toLowerCase();if(type.includes('pdf')||name.endsWith('.pdf'))return['PDF','📕'];if(type.startsWith('image/')||/\.(png|jpe?g|webp|gif)$/i.test(name))return['IMAGE','🖼️'];if(type.startsWith('text/')||name.endsWith('.txt'))return['TEXT','📝'];if(/\.(doc|docx)$/i.test(name))return['DOC','📄'];return['FILE','📎']}
  function crochetToast(msg){if(typeof toast==='function')toast(msg);else console.log(msg)}
  function crochetOpenDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE)){const store=db.createObjectStore(STORE,{keyPath:'id'});store.createIndex('createdAt','createdAt',{unique:false});store.createIndex('category','category',{unique:false});store.createIndex('status','status',{unique:false})}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async function crochetWithStore(mode,fn){const db=await crochetOpenDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),store=tx.objectStore(STORE);let result;try{result=fn(store)}catch(err){reject(err);return}if(result instanceof IDBRequest){result.onsuccess=()=>resolve(result.result);result.onerror=()=>reject(result.error)}else{tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Storage transaction cancelled'))}})}finally{db.close()}}
  const crochetGetAll=()=>crochetWithStore('readonly',s=>s.getAll()),crochetGet=id=>crochetWithStore('readonly',s=>s.get(id)),crochetPut=rec=>crochetWithStore('readwrite',s=>s.put(rec)),crochetRemove=id=>crochetWithStore('readwrite',s=>s.delete(id));
  function crochetCategoryOptions(selected='Other',includeAll=false){return(includeAll?['All',...CATEGORIES]:CATEGORIES).map(x=>`<option value="${crochetEsc(x)}" ${x===selected?'selected':''}>${crochetEsc(x)}</option>`).join('')}
  function crochetStatusOptions(selected='Saved',includeAll=false){return(includeAll?['All',...STATUSES]:STATUSES).map(x=>`<option value="${crochetEsc(x)}" ${x===selected?'selected':''}>${crochetEsc(x)}</option>`).join('')}
  function ensureCrochetNav(){if(document.querySelector('.nav-btn[data-view="crochet"]'))return;const ref=document.querySelector('.nav-btn[data-view="review"]'),sidebar=document.getElementById('sidebar');if(!sidebar)return;const btn=document.createElement('button');btn.className='nav-btn';btn.dataset.view='crochet';btn.innerHTML='<span class="nav-ico">🧶</span>Crochet Patterns';btn.onclick=()=>nav('crochet');if(ref)ref.parentNode.insertBefore(btn,ref);else sidebar.appendChild(btn)}
  function crochetHeroMarkup(){return`<div class="crochet-hero"><div class="crochet-hero-yarn" aria-hidden="true">🧶</div><div><div class="eyebrow">LUNA'S YARN SHELF</div><h2>My Crochet Pattern Library</h2><p>Keep PDFs, screenshots and saved patterns together — searchable, tagged and ready when the crochet mood hits.</p></div><div class="crochet-hero-actions"><button class="btn primary" onclick="crochetAddPattern()">＋ Add pattern</button><button class="btn" onclick="crochetQuickUpload()">⇧ Quick upload</button><input id="crochetQuickFiles" type="file" multiple hidden accept=".pdf,.png,.jpg,.jpeg,.webp,.gif,.txt,.doc,.docx,application/pdf,image/*,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"></div></div>`}
  function crochetShellMarkup(){return`<div class="crochet-page">${crochetHeroMarkup()}<div class="crochet-stats" id="crochetStats"><div class="crochet-stat"><span>Patterns</span><b>—</b><small>saved here</small></div><div class="crochet-stat"><span>Working on</span><b>—</b><small>current WIPs</small></div><div class="crochet-stat"><span>Made</span><b>—</b><small>finished projects</small></div><div class="crochet-stat"><span>Favorites</span><b>—</b><small>easy to find</small></div></div><div class="card crochet-toolbar-card"><div class="crochet-toolbar"><label class="crochet-search"><span>⌕</span><input id="crochetSearch" placeholder="Search patterns, tags or notes…" value="${crochetEsc(crochetFilters.search)}"></label><select id="crochetCategoryFilter" aria-label="Pattern category">${crochetCategoryOptions(crochetFilters.category,true)}</select><select id="crochetStatusFilter" aria-label="Project status">${crochetStatusOptions(crochetFilters.status,true)}</select><button class="btn" onclick="crochetExportIndex()">⇩ Export list</button></div><div class="crochet-storage-note"><b>Stored on this device ✨</b> Your pattern files live in House of Achen's private browser storage, separate from app updates. Download any must-keep originals as a backup before clearing Chrome/app data.</div></div><div id="crochetLibrary" class="crochet-library"><div class="crochet-loading">Opening your yarn shelf… 🧶</div></div></div>`}
  async function renderCrochet(){const host=document.getElementById('content'),title=document.getElementById('pageTitle');if(title)title.textContent='Crochet Pattern Library';if(!host)return;host.innerHTML=crochetShellMarkup();ensureCrochetNav();document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='crochet'));const search=document.getElementById('crochetSearch'),cat=document.getElementById('crochetCategoryFilter'),status=document.getElementById('crochetStatusFilter'),quick=document.getElementById('crochetQuickFiles');if(search)search.oninput=()=>{crochetFilters.search=search.value;crochetPaintLibrary()};if(cat)cat.onchange=()=>{crochetFilters.category=cat.value;crochetPaintLibrary()};if(status)status.onchange=()=>{crochetFilters.status=status.value;crochetPaintLibrary()};if(quick)quick.onchange=()=>crochetHandleQuickFiles(quick.files);await crochetPaintLibrary()}
  function crochetMatches(rec){if(crochetFilters.category!=='All'&&rec.category!==crochetFilters.category)return false;if(crochetFilters.status!=='All'&&rec.status!==crochetFilters.status)return false;const q=crochetFilters.search.trim().toLowerCase();if(!q)return true;return[rec.title,rec.fileName,rec.category,rec.status,rec.tags,rec.notes,rec.source].filter(Boolean).join(' ').toLowerCase().includes(q)}
  function crochetCard(rec){const[kind,icon]=crochetFileKind(rec),tags=String(rec.tags||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,5);return`<article class="crochet-card ${rec.favorite?'favorite':''}"><div class="crochet-card-top"><div class="crochet-file-icon"><span>${icon}</span><small>${kind}</small></div><button class="crochet-fav" onclick="crochetToggleFavorite('${crochetEsc(rec.id)}')" title="${rec.favorite?'Remove favorite':'Favorite'}">${rec.favorite?'★':'☆'}</button></div><div class="crochet-card-body"><div class="crochet-badges"><span class="crochet-chip category">${crochetEsc(rec.category||'Other')}</span><span class="crochet-chip status status-${crochetEsc((rec.status||'Saved').toLowerCase().replace(/\s+/g,'-'))}">${crochetEsc(rec.status||'Saved')}</span></div><h3>${crochetEsc(rec.title||crochetTitleFromName(rec.fileName))}</h3><div class="crochet-file-name">${crochetEsc(rec.fileName||'Uploaded pattern')} · ${crochetFormatBytes(rec.size||0)}</div>${rec.notes?`<p>${crochetEsc(rec.notes)}</p>`:''}${tags.length?`<div class="crochet-tags">${tags.map(t=>`<span>#${crochetEsc(t.replace(/^#/,'').trim())}</span>`).join('')}</div>`:''}</div><div class="crochet-card-foot"><small>Added ${crochetDate(rec.createdAt)}</small><div class="crochet-actions"><button class="btn tiny primary" onclick="crochetOpenPattern('${crochetEsc(rec.id)}')">Open</button><button class="btn tiny" onclick="crochetEditPattern('${crochetEsc(rec.id)}')">Edit</button><button class="btn tiny" onclick="crochetDownloadPattern('${crochetEsc(rec.id)}')">⇩</button><button class="btn tiny danger" onclick="crochetDeletePattern('${crochetEsc(rec.id)}')">×</button></div></div></article>`}
  async function crochetPaintLibrary(){const host=document.getElementById('crochetLibrary');if(!host)return;try{const all=(await crochetGetAll()).sort((a,b)=>(Number(b.favorite)-Number(a.favorite))||String(b.createdAt||'').localeCompare(String(a.createdAt||''))),filtered=all.filter(crochetMatches),stats=document.getElementById('crochetStats');if(stats){const values=[all.length,all.filter(x=>x.status==='Working on it').length,all.filter(x=>x.status==='Made').length,all.filter(x=>x.favorite).length];stats.querySelectorAll('b').forEach((el,i)=>el.textContent=values[i]??0)}if(!all.length){host.innerHTML='<div class="crochet-empty card"><div class="crochet-empty-yarn">🧶</div><h3>Your yarn shelf is waiting</h3><p>Upload a PDF, photo, screenshot or document and House of Achen will keep it here for you.</p><button class="btn primary" onclick="crochetAddPattern()">Add your first pattern</button></div>';return}if(!filtered.length){host.innerHTML='<div class="crochet-empty card"><div class="crochet-empty-yarn">🔎</div><h3>No patterns match that</h3><p>Try a different search, category or project status.</p><button class="btn" onclick="crochetClearFilters()">Clear filters</button></div>';return}host.innerHTML=`<div class="crochet-grid">${filtered.map(crochetCard).join('')}</div>`}catch(err){console.error(err);host.innerHTML='<div class="card crochet-empty"><h3>Pattern storage could not open</h3><p>Try refreshing House of Achen. Your other app data was not changed.</p></div>'}}
  function crochetAddPattern(){if(typeof openModal!=='function')return;openModal('Add crochet pattern',`<div class="crochet-form"><label class="crochet-upload-drop">🧶<b>Choose a pattern file</b><span>PDF, image, TXT or Word document · up to 50 MB</span><input id="crochetFile" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.gif,.txt,.doc,.docx,application/pdf,image/*,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"></label><div class="form-grid"><label>Pattern name<input id="crochetTitleInput" placeholder="e.g. Ruffle bathroom rag"></label><label>Category<select id="crochetCategoryInput">${crochetCategoryOptions('Other')}</select></label><label>Status<select id="crochetStatusInput">${crochetStatusOptions('Saved')}</select></label><label>Tags<input id="crochetTagsInput" placeholder="cotton, easy, gift"></label><label class="span2">Pattern source / link<input id="crochetSourceInput" placeholder="Etsy, Ravelry, website, designer…"></label><label class="span2">Notes<textarea id="crochetNotesInput" placeholder="Hook size, yarn ideas, changes I want to make…"></textarea></label></div></div>`,`<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="crochetSaveNewPattern()">Save pattern</button>`);const input=document.getElementById('crochetFile');input?.addEventListener('change',()=>{const title=document.getElementById('crochetTitleInput');if(title&&!title.value&&input.files?.[0])title.value=crochetTitleFromName(input.files[0].name)})}
  async function crochetSaveNewPattern(){const file=document.getElementById('crochetFile')?.files?.[0];if(!file){alert('Choose a pattern file first.');return}if(file.size>MAX_FILE_BYTES){alert('That file is over 50 MB. Please use a smaller copy.');return}const rec={id:crochetId(),title:(document.getElementById('crochetTitleInput')?.value||crochetTitleFromName(file.name)).trim(),category:document.getElementById('crochetCategoryInput')?.value||'Other',status:document.getElementById('crochetStatusInput')?.value||'Saved',tags:(document.getElementById('crochetTagsInput')?.value||'').trim(),source:(document.getElementById('crochetSourceInput')?.value||'').trim(),notes:(document.getElementById('crochetNotesInput')?.value||'').trim(),favorite:false,fileName:file.name,mimeType:file.type||'application/octet-stream',size:file.size,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),file};try{await crochetPut(rec);if(typeof closeModal==='function')closeModal();crochetToast('Pattern saved to your yarn shelf 🧶');await crochetPaintLibrary()}catch(err){console.error(err);alert('I could not save that file in browser storage.')}}
  function crochetQuickUpload(){document.getElementById('crochetQuickFiles')?.click()}
  async function crochetHandleQuickFiles(fileList){const files=[...(fileList||[])];if(!files.length)return;let saved=0,skipped=0;for(const file of files){if(file.size>MAX_FILE_BYTES){skipped++;continue}await crochetPut({id:crochetId(),title:crochetTitleFromName(file.name),category:'Other',status:'Saved',tags:'',source:'',notes:'',favorite:false,fileName:file.name,mimeType:file.type||'application/octet-stream',size:file.size,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),file});saved++}crochetToast(`${saved} pattern${saved===1?'':'s'} added${skipped?` · ${skipped} skipped (over 50 MB)`:''}`);const input=document.getElementById('crochetQuickFiles');if(input)input.value='';await crochetPaintLibrary()}
  async function crochetEditPattern(id){const rec=await crochetGet(id);if(!rec)return;openModal('Edit crochet pattern',`<div class="crochet-form"><div class="crochet-edit-file">📎 <b>${crochetEsc(rec.fileName)}</b><span>${crochetFormatBytes(rec.size)}</span></div><div class="form-grid"><label>Pattern name<input id="crochetEditTitle" value="${crochetEsc(rec.title||'')}"></label><label>Category<select id="crochetEditCategory">${crochetCategoryOptions(rec.category||'Other')}</select></label><label>Status<select id="crochetEditStatus">${crochetStatusOptions(rec.status||'Saved')}</select></label><label>Tags<input id="crochetEditTags" value="${crochetEsc(rec.tags||'')}" placeholder="cotton, easy, gift"></label><label class="span2">Pattern source / link<input id="crochetEditSource" value="${crochetEsc(rec.source||'')}"></label><label class="span2">Notes<textarea id="crochetEditNotes">${crochetEsc(rec.notes||'')}</textarea></label></div></div>`,`<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="crochetSaveEdits('${crochetEsc(id)}')">Save changes</button>`)}
  async function crochetSaveEdits(id){const rec=await crochetGet(id);if(!rec)return;rec.title=(document.getElementById('crochetEditTitle')?.value||rec.title).trim();rec.category=document.getElementById('crochetEditCategory')?.value||rec.category;rec.status=document.getElementById('crochetEditStatus')?.value||rec.status;rec.tags=(document.getElementById('crochetEditTags')?.value||'').trim();rec.source=(document.getElementById('crochetEditSource')?.value||'').trim();rec.notes=(document.getElementById('crochetEditNotes')?.value||'').trim();rec.updatedAt=new Date().toISOString();await crochetPut(rec);closeModal();crochetToast('Pattern updated ✨');await crochetPaintLibrary()}
  async function crochetToggleFavorite(id){const rec=await crochetGet(id);if(!rec)return;rec.favorite=!rec.favorite;rec.updatedAt=new Date().toISOString();await crochetPut(rec);await crochetPaintLibrary()}
  async function crochetDeletePattern(id){const rec=await crochetGet(id);if(!rec)return;if(!confirm(`Remove “${rec.title||rec.fileName}” from your crochet library? This deletes the saved copy from this device.`))return;await crochetRemove(id);crochetToast('Pattern removed');await crochetPaintLibrary()}
  function crochetCloseViewer(){document.getElementById('crochetViewer')?.remove();if(crochetViewerUrl){URL.revokeObjectURL(crochetViewerUrl);crochetViewerUrl=null}}
  async function crochetOpenPattern(id){const rec=await crochetGet(id);if(!rec?.file)return;crochetCloseViewer();const type=rec.mimeType||'';crochetViewerUrl=URL.createObjectURL(rec.file);let body='';if(type.startsWith('image/')||/\.(png|jpe?g|webp|gif)$/i.test(rec.fileName||'')){body=`<img src="${crochetViewerUrl}" alt="${crochetEsc(rec.title||rec.fileName)}">`}else if(type.includes('pdf')||/\.pdf$/i.test(rec.fileName||'')){body=`<iframe src="${crochetViewerUrl}#view=FitH" title="${crochetEsc(rec.title||rec.fileName)}"></iframe>`}else if(type.startsWith('text/')||/\.txt$/i.test(rec.fileName||'')){const text=await rec.file.text();body=`<pre>${crochetEsc(text)}</pre>`}else{crochetDownloadPattern(id);crochetCloseViewer();return}const viewer=document.createElement('div');viewer.id='crochetViewer';viewer.className='crochet-viewer';viewer.innerHTML=`<div class="crochet-viewer-head"><div><span>🧶 CROCHET PATTERN</span><b>${crochetEsc(rec.title||rec.fileName)}</b></div><div><button class="btn" onclick="crochetDownloadPattern('${crochetEsc(id)}')">⇩ Download</button><button class="btn" onclick="crochetCloseViewer()">Close ×</button></div></div><div class="crochet-viewer-stage">${body}</div>`;document.body.appendChild(viewer)}
  async function crochetDownloadPattern(id){const rec=await crochetGet(id);if(!rec?.file)return;const url=URL.createObjectURL(rec.file),a=document.createElement('a');a.href=url;a.download=rec.fileName||`${rec.title||'crochet-pattern'}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
  async function crochetExportIndex(){const rows=(await crochetGetAll()).map(({file,...meta})=>meta),payload={exportedAt:new Date().toISOString(),note:'Pattern-library index only. Original pattern files are not embedded in this JSON.',patterns:rows},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`house-of-achen-crochet-library-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function crochetClearFilters(){crochetFilters={search:'',category:'All',status:'All'};const s=document.getElementById('crochetSearch');if(s)s.value='';const c=document.getElementById('crochetCategoryFilter');if(c)c.value='All';const st=document.getElementById('crochetStatusFilter');if(st)st.value='All';crochetPaintLibrary()}
  Object.assign(window,{crochetAddPattern,crochetSaveNewPattern,crochetQuickUpload,crochetEditPattern,crochetSaveEdits,crochetToggleFavorite,crochetDeletePattern,crochetOpenPattern,crochetCloseViewer,crochetDownloadPattern,crochetExportIndex,crochetClearFilters});
  ensureCrochetNav();try{if(typeof LUNA_TIPS!=='undefined')LUNA_TIPS.crochet='Your pattern shelf is for the patterns you actually want to find again. Tag the good ones, mark your WIPs, and let the yarn chaos stay cute.'}catch{}
  const crochetBaseRender=render;render=function(){if(currentView==='crochet'){renderCrochet();return}const result=crochetBaseRender();ensureCrochetNav();return result};if(currentView==='crochet')renderCrochet();
})();